dist: focal
language: java
jdk: openjdk11
install:
  - mvn dependency:go-offline -V
script:
  - mvn install
notifications:
  email:
    recipients:
      - sanyakovlev@yandex.ru
    on_success: never
    on_failure: always